### ISSUE TITLE
Page: Error Page

### ISSUE THREAD

**Issue by Ddan71117** [Ddan71117/stallStarz#5]
Adding a unique 404 page.

**Comment by sunny-script** [comment]
Have added code to my branch, waiting on api routes to update and test within code. Will push once final.

**Comment by sunny-script** [comment]
// ERROR HANDLING FILE

import React from "react";
import { Link } from "react-router-dom";

const NotFound: React.FC = () => {
  return (
    <div className="not-found">
      <h1>404 - Page Not Found</h1>
      <p>Sorry, the page you're looking for doesn't exist. Must have been flushed.</p>
      <Link to="/app.tsx">Go Back Home</Link>
    </div>
  );
};

export default NotFound;


// ERROR ROUTES FILE

import { Routes, Route } from 'react-router-dom';
import ErrorHandling from './components/errorHandling';

// TODO: Need to import additional and relevant routes for error handling
const AppRoutes: React.FC = () => {
  return (
    <Routes>
      <Route path="*" element={<ErrorHandling />} />
    </Routes>
  );
};

export default AppRoutes;
